ekf_fastlio_gt:
  ros__parameters:
    use_sim_time: false
    frequency: 30.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: blueboat/base_link_enu
    world_frame: map

    odom0: /Odometry
    odom0_config: [true, true, false,
                   false, false, true,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom0_relative: false
    odom0_queue_size: 20

    odom1: /blueboat/navigator/odometry
    odom1_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_relative: false
    odom1_queue_size: 10